apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:7.1
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          volumeMounts:
          - mountPath: "/opt/sonarqube/data/"
            name: sonar-data
          - mountPath: "/opt/sonarqube/extensions/"
            name: sonar-extensions

          env:
          - name: "SONARQUBE_JDBC_USERNAME"
            valueFrom:
                secretKeyRef:
                  name: sonar-secret 
                  key: SONARQUBE_JDBC_USERNAME

          - name: "SONARQUBE_JDBC_URL"
            value: "jdbc:postgresql://postgres/sonar"
            
          - name: "SONARQUBE_JDBC_PASSWORD"
            valueFrom:
                secretKeyRef:
                  name: sonar-secret 
                  key: SONARQUBE_JDBC_PASSWORD 

          ports:
          - containerPort: 9000
            protocol: TCP
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data-pvc
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonar-extensions-pvc
